### ISSUE TITLE
橡皮擦 笔迹是 黑色。。

### ISSUE THREAD

**Issue by Myth1** [guanpy/WhiteBoard#4]

**Comment by keaitao0321** [comment]
这么修改橡皮擦笔迹颜色

**Comment by Myth1** [comment]
设置xFermode可以解决，具体看PorterDuffXfermode类

**Comment by keaitao0321** [comment]
/**
     * 初始化画笔
     */
    public void changeEraser() {
        mPaint.setColor(mContext.getResources().getColor(R.color.transparent));
        mPaint.setStrokeWidth(2 * OperationUtils.getInstance().mCurrentEraserSize);
        mPaint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.CLEAR));//擦除模式
        postInvalidate();
    }

这里么？设置成什么模式好呢 ？
